apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: elder-peeler
  labels:
    app: elder-peeler
    release: kp
spec:
  selector:
    matchLabels:
      app: elder-peeler
  podMetricsEndpoints:
  - interval: 15s

